exclude_paths:
  - tmp
  - vendor

detectors:
  FeatureEnvy:
    exclude:
      - Terminus::Actions::API::Images::Create#handle
      - Terminus::Screens::Greyscaler#convert
      - Terminus::Screens::Screensaver#save
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - Terminus::Screens::Greyscaler#convert
      - Terminus::Screens::Screensaver#save
      - Terminus::Views::Parts::Device#battery_percentage
      - Terminus::Views::Parts::Device#wifi_percentage
