exclude_paths:
  - tmp
  - vendor

detectors:
  Attribute:
    exclude:
      - Terminus::Views::Parts::User#password
  DataClump:
    exclude:
      - Terminus::Aspects::Screens::Shoter
  DuplicateMethodCall:
    exclude:
      - Terminus::Aspects::Extensions::Parsers::CSV#call
  FeatureEnvy:
    exclude:
      - Terminus::Actions::API::Screens::Create#handle
      - Terminus::Actions::API::Screens::Create#save
      - Terminus::Actions::Devices::Create#provision
      - Terminus::Actions::Devices::Create#render_new
      - Terminus::Actions::Devices::Update#edit
      - Terminus::Actions::Firmware::Delete#render
      - Terminus::Actions::Models::Update#error
      - Terminus::Actions::Playlists::Create#error
      - Terminus::Actions::Playlists::Update#error
      - Terminus::Actions::Users::Update#error
      - Terminus::Aspects::Screens::Compressor#convert
      - Terminus::Aspects::Screens::Converter#convert
      - Terminus::Aspects::Screens::Converters::BMP#convert
      - Terminus::Aspects::Screens::Converters::PNG#convert
      - Terminus::Aspects::Screens::Creators::TempPath#capture_input
      - Terminus::Aspects::Screens::Designer::EventStream#render_preview
      - Terminus::Aspects::Screens::Shoter#save
      - Terminus::IPFinder#all
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - Terminus::Action#handle_rodauth_redirect
      - Terminus::Aspects::Firmware::Downloader#get
      - Terminus::Aspects::Screens::ColorMapper#colorize
      - Terminus::Aspects::Screens::ColorMapper#run
      - Terminus::Aspects::Screens::Compressor#call
      - Terminus::Aspects::Screens::Converter#convert
      - Terminus::Aspects::Screens::Converters::BMP#convert
      - Terminus::Aspects::Screens::Converters::PNG#call
      - Terminus::Aspects::Screens::Converters::PNG#convert
      - Terminus::Aspects::Screens::Shoter#save
      - Terminus::Views::Parts::Device#battery_percentage
      - Terminus::Views::Parts::Device#wifi_percentage
