name: "terminus"

services:
  web:
    init: true
    build:
      context: .
      target: development
    env_file: .env.docker
    environment:
      API_URI: ${API_URI-http://localhost:2300}
      DATABASE_URL: postgres://${PG_USER:-postgres}:${PG_PASSWORD:-password}@database:5432/${PG_DATABASE:-terminus_development}
    ports:
      - "2300:2300"
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    command: ["bin/docker/dev"]
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  database:
    image: postgres:17.4
    env_file: .env.docker
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-terminus_development}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-postgres}"]
      interval: 5s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

volumes:
  database-data:
