:toc: macro
:toclevels: 5
:figure-caption!:

:docker_compose_link: link:https://docs.docker.com/compose[Docker Compose]
:docker_link: link:https://www.docker.com[Docker]
:ruby_link: link:https://www.ruby-lang.org[Ruby]

= Docker

We provide {docker_link} support in case you don't want to use our {ruby_link} stack. This includes both a development and production environment. In most cases, you'll want to use {docker_compose_link} to manage the stack. Pre-built Docker link:https://github.com/usetrmnl/byos_hanami/pkgs/container/terminus[images] for AMD 64 and ARM 64 are included as well.

Continue reading to learn more.

toc::[]

== Setup

To get setup, run:

[source,bash]
----
git clone https://github.com/usetrmnl/byos_hanami terminus
cd terminus
bin/setup docker
----

== Upgrade

To get upgrade, run:

[source,bash]
----
cd terminus
bin/upgrade docker
----

Watch for any changes that need to be addressed in the output. Otherwise, if no changes are detected, you are all set.

== Configuration

You'll want to customize the environment variables in your `.env` file so your device can connect. This is automatically setup for you but, depending on your specific needs, you'll want to customize further. Specifically, to ensure the `API_URI` and `HANAMI_PORT` environment variables are set for your host. See link:/#configuration[Configuration] for details.

💡 When making environment variable changes (or the `.env` file in general), ensure you restart Docker (or Docker Compose) to apply the changes.

== Images

To use pre-built images, run either of the following:

[source,bash]
----
# Latest
docker pull ghcr.io/usetrmnl/terminus:latest

# Specific version.
docker pull ghcr.io/usetrmnl/terminus:<version>
----

== Compose

Use {docker_compose_link} to quickly launch the entire stack for development or production environments. You can also update `compose.dev.yml` or `compose.yml` to use the pre-built or local images as follows:

*Local Image Only*

[source,yaml]
----
build:
  context: .
----

*Pre-Built Image Only*

[source,yaml]
----
image: ghcr.io/usetrmnl/terminus:latest
----

Further details can be found in the `compose.yml` or `compose.dev.yml` files at the root of this project.

== Development

To launch the development stack, run:

[source,bash]
----
docker-compose --file compose.dev.yml up
----

== Production

To launch the production stack, run:

[source,bash]
----
docker-compose up
----

== Troubleshooting

When using the _Quick Start_ or _Setup_ scripts, they will create a `.env` file which is picked up by Docker Compose. The two critical environment variables to pay attention to are:

* `API_URI`: This needs to be updated if your server IP address has changed or when the setup script failed to automatically detect your IP address. Your device also needs this URI in order to connect to your server. So both your server and device must be using the same URI.
* `DATABASE_PASSWORD` or `KEYVALUE_PASSWORD`: These are automatically generated for you during setup but if you regenerate the `.env` file or change these values, you'll lose access to your database. When access is lost, there are two ways to fix:
** Use PostgreSQL admin access or Redis to update to the password used in your `.env` file.
** Delete the associated service volume and then launch `docker-compose up` again. The volume can be identified as: `+terminus-<environment>_<service>-data+`. You'll lose all of your data but will be able to setup your device again.
* If your extension worker fails to fetch data from resources protected by self-signed certificates, you can add `CERTIFICATE_URLS=...` to download and install the appropriate signing certificate(s) during `docker compose up`.
