:toc: macro
:toclevels: 5
:figure-caption!:

:core_link: link:https://trmnl.com[Core]

= Jobs

All background jobs are handled by the Sidekiq worker service. Most are created via the UI but a few are launched at application boot. The following jobs are launched at application boot by caching data from our {core_link} server for improved performance and to keep common records in sync:

* *Firmware*: Downloads the latest firmware for updating your local devices. Ensure you have enabled firmware updates for your devices if you'd like to have these updated applied automatically. By default, this checks for updates every six hours. In situations where your device updated to a newer Firmware version and it was a bad/broken version, you can revert to and older version by following these steps:
** Ensure the device you want to downgrade has firmware updates turned on (you'll also want to ensure devices you don't want to downgrade have this setting _turned off_).
** Visit the Firmwares page within the UI.
** Delete all latest versions until you only have the version you want to downgrade to listed at the top of the list.
** Short click the button on the back of your device to force a refresh and wait for the firmware downgrade to complete.
* *Model*: Synchronizes model information from the {core_api_link}. New models, as they become available, are added to the database while existing models, if updated, will be updated. By default, this checks for updates once a day.
* *Screen*: Downloads device screens for any device you have set up to proxy to the Core server. You only need to toggle _proxy_ support for any/all devices you want to pull from Core. This allows you to leverage any/all recipes/plugins you have configured via your remote account. By default, this checks for updates every five minutes.

== Configuration

The configuration and cron schedule for all of these jobs can be found in the `config/sidekiq_scheduler.yml` file.

== Restarts

For local development, you can use {overmind_link} to restart the worker service which cause all jobs defined in `config/sidekiq_scheduler.yml` to be rerun. Example:

[source,bash]
----
overmind restart worker
----

This can be handy if you want to force an update.

== Disablement

To disable any of the pollers, use the following environment variables:

----
FIRMWARE_POLLER=0
MODEL_POLLER=0
SCREEN_POLLER=0
----

You are not limited to using `0`. Any falsey value would work, example: `false`, "no", etc. When any of the pollers are disabled, you'll see the following messages in your logs (where `<poller>` is replaced with the specific poller that is disabled):

----
<poller> polling disabled.
----

