:toc: macro
:toclevels: 5
:figure-caption!:

:pi_project_link: link:https://alchemists.io/projects/pi[Pi]

= Raspberry Pi

We support Raspberry Pi and have tested using the following:

* link:https://www.raspberrypi.com/products/raspberry-pi-5[Raspberry Pi 5]: Recommended due to great performance and feature set.
* link:https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/[Raspberry Pi Zero 2 W]: Good if you want a compact form factor and don't care about speed.

A great project to help you manage multiple Raspberry Pi devices and configurations is the {pi_project_link} project. This project provides Bash shell scripts for formatting, installing the Raspberry Pi OS, and spinning up Terminus.

For Terminus, you only need to add the following to your `projects` configuration (i.e. `$XDG_CONFIG_HOME/pi/scripts/projects`):

[source,bash]
----
#! /usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'

git clone https://github.com/usetrmnl/byos_hanami terminus
cd terminus
bin/setup docker
----

Then you can run `bin/run s` to format and configure your micro SSD card and run a dockerized version of Terminus on your Raspberry Pi device. Finally, once your Raspberry Pi has booted, you can SSH in to launch Terminus. Example:

[source,bash]
----
ssh admin@demo.local
cd terminus
docker compose up
----

This would allow you to visit `http://demo.local:2300` in your browser to register/login and start using Terminus. That's it!

Definitely check out the {pi_project_link} project for more details.
