apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terminus.fullname" . }}-uploads
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.uploads.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terminus.fullname" . }}-fonts
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.fonts.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.fonts.size }}
