{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terminus.serviceAccountName" . }}
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- include "terminus.stringMap" . | trim | nindent 4 }}
  {{- end }}
{{- end }}
