services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/terminus_development
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db:
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - ${DB_HOST_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: terminus_development

volumes:
  postgres-data:
