names:
  - BlockKie.ttf
  - Inter-Italic.ttf
  - Inter.ttf
  - NicoClean-Regular.ttf
  - NicoPups-Regular.ttf
  - TRMNL12-Bold.ttf
  - TRMNL12-Bold.woff
  - TRMNL12-Bold.woff2
  - TRMNL12-Regular.ttf
  - TRMNL12-Regular.woff
  - TRMNL12-Regular.woff2
  - TRMNL16-Bold.ttf
  - TRMNL16-Bold.woff
  - TRMNL16-Bold.woff2
  - TRMNL16-Regular.ttf
  - TRMNL16-Regular.woff
  - TRMNL16-Regular.woff2
  - TRMNL21-Bold.ttf
  - TRMNL21-Bold.woff
  - TRMNL21-Bold.woff2
  - TRMNL21-Regular.ttf
  - TRMNL21-Regular.woff
  - TRMNL21-Regular.woff2
